### ISSUE TITLE
Again... No valid Links available 

### ISSUE THREAD

**Issue by ghost** [BuXXe/movian-kinox-plugin#1]
After my brother updated Movian i got this error again if i try to use the Kinox.to Plugin.

Would it be possible to fix this Issue and could you tell me which Movian Version you are using?

**Comment by BuXXe** [comment]
The no valid links is just the indicator that a link resolver could not get the correct movie file from the hoster (so the file could be offline (404) or my resolver could be broken). I use Movian v4 (in fact: 4.10.35.g83bb6) integrated in Multiman on my PS3. I do not support Movian 5.0 officially because i dont like it yet and will not test against it. 

It is possible that my resolvers for the different hosters get outdated when the hosters change their streaming codes. So if you could provide me some examples for movies with the hosters you can not use and perhaps the log files, I can further investigate on this issue. (I already know that FlashX seems to have changed its hosting style and perhaps needs an updated resolver).

**Comment by ghost** [comment]
It happens with every video and every hoster

**Comment by ghost** [comment]
Just tried it with Movian 4.10.35... No Problems
Movian 5.0.7... Not Working (No valid Links available)

**Comment by BuXXe** [comment]
Yeah as said, Movian 5 is not officially supported. It changed a lot under the hood so there could be many issues regarding requests and such. If there will ever be a reason for switching to Movian 5.0 I will revisit the plugins but as long as I can use them with 4, I guess you have to stick to it too.

**Comment by ghost** [comment]
Yeah no problem. My Last Post was just to inform you about the problem
